import React, { createContext, useContext, useState } from 'react';
import {
  INITIAL_USER,
  INITIAL_STATS,
  RECENT_CAMPAIGNS_DATA,
} from '../data/campaignData';

const CampaignContext = createContext();

export function CampaignProvider({ children }) {
  const [page, setPage] = useState('landing'); // 'landing' | 'dashboard' | 'results' | 'videopreview' | 'settings' | 'mycampaigns'
  const [user, setUser] = useState(INITIAL_USER);
  const [stats, setStats] = useState(INITIAL_STATS);
  const [campaigns, setCampaigns] = useState(RECENT_CAMPAIGNS_DATA);
  const [currentCampaign, setCurrentCampaign] = useState(RECENT_CAMPAIGNS_DATA[0]);
  const [selectedVariantIndex, setSelectedVariantIndex] = useState(0);
  const [toastMessage, setToastMessage] = useState(null);

  const triggerToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const createCampaign = ({ description, audience, platform, budget }) => {
    if (!description.trim()) {
      triggerToast('Please enter a product description.');
      return;
    }

    const noun = description.trim().split(/\s+/).slice(0, 2).join(' ') || 'Product';
    const title = noun.charAt(0).toUpperCase() + noun.slice(1) + ' Campaign';

    const newVariants = [
      {
        id: `var-${Date.now()}-1`,
        name: 'Variant 1',
        score: 92,
        headline: `${noun.toUpperCase()} — Crystal Clear Performance`,
        caption: 'Experience high-converting ad copy generated by AI in seconds.',
        cta: 'Get Yours Today',
        overlayText: 'Small Size. Big Sound.',
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-wireless-earbuds-42998-large.mp4',
        duration: '15 seconds',
        resolution: `1080 x 1080 (${platform})`,
        format: 'MP4',
      },
      {
        id: `var-${Date.now()}-2`,
        name: 'Variant 2',
        score: 78,
        headline: `Freedom In Every Detail`,
        caption: 'Engineered to captivate your audience and boost CTR.',
        cta: 'Shop Now',
        overlayText: 'Music In Your World',
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-wireless-earbuds-42998-large.mp4',
        duration: '15 seconds',
        resolution: `1080 x 1080 (${platform})`,
        format: 'MP4',
      },
      {
        id: `var-${Date.now()}-3`,
        name: 'Variant 3',
        score: 85,
        headline: `Premium Quality Everyday`,
        caption: 'Designed for high engagement across social channels.',
        cta: 'Buy Now',
        overlayText: 'Premium Sound For Everyday',
        imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-close-up-of-wireless-earbuds-42998-large.mp4',
        duration: '15 seconds',
        resolution: `1080 x 1080 (${platform})`,
        format: 'MP4',
      },
    ];

    const newCamp = {
      id: `camp-${Date.now()}`,
      title,
      description,
      platform,
      audience,
      budget,
      status: 'Completed',
      timeAgo: 'Just now',
      score: 92,
      variants: newVariants,
    };

    setCampaigns([newCamp, ...campaigns]);
    setCurrentCampaign(newCamp);
    setSelectedVariantIndex(0);
    setStats((prev) => ({
      totalCampaigns: prev.totalCampaigns + 1,
      adsGenerated: prev.adsGenerated + 3,
      avgEngagementScore: prev.avgEngagementScore,
    }));
    setUser((prev) => ({
      ...prev,
      creditsUsed: Math.min(prev.creditsUsed + 3, prev.totalCredits),
    }));

    triggerToast('Campaign created successfully!');
    setPage('results');
  };

  const viewCampaign = (campId) => {
    const found = campaigns.find((c) => c.id === campId);
    if (found) {
      setCurrentCampaign(found);
      setSelectedVariantIndex(0);
      setPage('results');
    }
  };

  const viewVideoPreview = (variantIndex = 0) => {
    setSelectedVariantIndex(variantIndex);
    setPage('videopreview');
  };

  const updateUser = (name, email) => {
    setUser((prev) => ({ ...prev, name, email }));
    triggerToast('Profile settings saved successfully!');
  };

  return (
    <CampaignContext.Provider
      value={{
        page,
        setPage,
        user,
        stats,
        campaigns,
        currentCampaign,
        selectedVariantIndex,
        setSelectedVariantIndex,
        createCampaign,
        viewCampaign,
        viewVideoPreview,
        updateUser,
        toastMessage,
        triggerToast,
      }}
    >
      {children}
    </CampaignContext.Provider>
  );
}

export function useCampaign() {
  const context = useContext(CampaignContext);
  if (!context) {
    throw new Error('useCampaign must be used within a CampaignProvider');
  }
  return context;
}
